- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs:20 
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  
  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the catalogue code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  
  - name: Extract the code in app directory
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes         #means file already exists in ansible control server remote machine. If don't give it will fail

  - name: Install npm dependencies
    community.general.npm:            #It's a community module which helps in installing npm dependencies
      path: /app
  
  - name: copy catalogue service to system directory
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Reload the service
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: start and enable catalogue service
    ansible.builtin.service:
      name: catalogue 
      state: started
      enabled: yes
  
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present
  
  - name: check products or loaded or not
    ansible.builtin.command: mongosh --host mongodb.roboshop.space --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: db_output    # To extract the output from the abobe command. Similar like $() in shell

  - name: Print the output
    ansible.builtin.debug:
      msg: "{{ db_output }}"

  - name: Load the products to db
    ansible.builtin.shell: mongosh --host mongodb.roboshop.space <app/db/master-data.Js
    when: db_output.stdout | int < 0  

  
