- name: frontend component
  hosts: frontend
  become: yes
  tasks:
  - name: Disable nginx
    ansible.builtin.command: dnf module disable nginx -y
  
  - name: Enable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y
  
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: Remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent                    # This will remove the default directory 

  - name: Create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory 

  - name: Download the content
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip
  
  - name: Extract the frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  
  - name: Remove default nginx conf file
    ansible.builtin.file:
      src: /etc/nginx/nginx.conf      # we are deleting cuz it will create by default when nginx installed
      state: absent
  
  - name: copy roboshop nginx conf
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  
  - name: Restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
  

  


      