- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: Install Maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - maven
    - mysql

  # Install python packages to load schema db which are some dependent packages
  - name: Install PyMySQL and Cyrptography
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - Cyrptography
    - PyMySQL
  
  - name: create system user
    ansible.builtin.user:
      name: roboshop 
      shell: /sbin/nologin
      system: true
      home: /app
  
  - name: create an app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download the application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip
  
  - name: Extracting the shipping code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
  
  # As we don't have any official ansible module for mvn dependencies we go for shell command module. 
  # args is used to download the dependencies in a special path
  - name: Install maven Dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app 
  
  - name: Rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app
  
  - name: copy shipping service in systemd
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  
  - name: Reload the service
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: start and enable the service
    ansible.builtin.service:
      name: shipping 
      state: started
      enabled: yes

# importing DB schema data to files
  - name: import data 
    tags:
    - import #It used to run this specific task only
    community.mysql.mysql_db:   #This will connect to DB and load the load based on params below
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.roboshop.space
      state: import
      target: "{{ item }}" 
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: Restart the service
    tags:
    - import
    ansible.builtin.service:
      name: shipping
      state: restarted
  
